Responsive
wolox-training/eg-angular-js pull request #10
Opened 2018-12-19 20:42 UTC by eledwinn

## Summary
- Add responsive design to index

## Screenshot
![dec-19-2018 15-41-07](https://user-images.githubusercontent.com/2124740/50246939-9f153d80-03a4-11e9-8881-a5ee795894b6.gif)

## Trello Card
https://trello.com/c/09VPBERC/15-dise%C3%B1o-responsive

2018-12-20 12:38 UTC, FrankIglesias requested changes

2018-12-20 12:38 UTC, FrankIglesias commented on scss/footer.scss
> +  max-width: 90%;
why this width?

2018-12-20 12:38 UTC, FrankIglesias commented on scss/footer.scss
> +    margin: 50px 0px;
remove the px suffix

2018-12-20 12:38 UTC, FrankIglesias commented on scss/styles.scss
> +  .body{
add a space before the curly brace

2018-12-20 12:38 UTC, FrankIglesias commented on scss/titles.scss
> +
remove this line

2018-12-20 15:25 UTC, eledwinn commented on scss/footer.scss
> +  max-width: 90%;
When screen width is less than image width, the screen looks like this:

![image](https://user-images.githubusercontent.com/2124740/50293247-24e6c680-0441-11e9-80b2-b951729a9fa6.png)

That's why the with property was added.

2018-12-26 15:40 UTC, FrankIglesias commented on scss/footer.scss
> +  max-width: 90%;
```scss
width: 100%;
max-width: 300px;
```

2018-12-26 15:53 UTC, FrankIglesias approved these changes

2018-12-26 15:54 UTC, merged