Books dashboard
wolox-training/eg-angular-js pull request #11
Opened 2018-12-26 23:02 UTC by eledwinn

## Summary
1. Dashboard & books list
2. Input component

## Screenshot
![image](https://user-images.githubusercontent.com/2124740/50459342-372c9d00-0938-11e9-80e9-ab865ed9450f.png)

##Trello Card
https://trello.com/c/ZpxLhdGg/15-wbooks

2018-12-30 02:26 UTC, FrankIglesias requested changes
You can optionally add a linter checker like [this one](https://eslint.org/)

2018-12-30 02:26 UTC, FrankIglesias commented on .gitignore
> +.idea
add EOL

2018-12-30 02:26 UTC, FrankIglesias commented on app/scss/book-item.scss
> +  margin: 0 30px 30px 30px;
margin: 0 30px 30px;

2018-12-30 02:26 UTC, FrankIglesias commented on app/scss/book-item.scss
> +  width: 128px;
don't use both values as fixed

2018-12-30 02:26 UTC, FrankIglesias commented on app/scss/w-input.scss
> +  .fa {
what is this fa?

2018-12-30 02:26 UTC, FrankIglesias commented on app/scss/w-input.scss
> +  display: inline-block;
avoid copy pasting from the sketch like this. Use px and avoid mixing em and px in a calc

2018-12-30 02:26 UTC, FrankIglesias commented on app/scss/w-input.scss
> +  text-shadow: 0 0 0 #000;
use color variables

2018-12-30 02:26 UTC, FrankIglesias commented on app/scss/w-input.scss
> +  /* reset */
remove this comment

2018-12-30 02:26 UTC, FrankIglesias commented on app/scss/w-input.scss
> +  -webkit-box-sizing: border-box;
remove this two lines

2018-12-30 02:26 UTC, FrankIglesias commented on app/scss/w-input.scss
> +  -webkit-appearance: none;
same with theese

2018-12-30 02:26 UTC, FrankIglesias commented on app/scss/w-input.scss
> +.w-select:-moz-focusring {
same

2018-12-30 02:26 UTC, FrankIglesias commented on app/scss/equalizer.scss
> +$equalizer-black: #000;
you can now use [wolox equalizer](https://www.npmjs.com/package/wolox-equalizer) from npm

2018-12-30 02:26 UTC, FrankIglesias commented on package.json
> +    "postinstall": "npm run copy-libs",
remove some extra tasks here...

2018-12-30 02:26 UTC, FrankIglesias commented on app/index.html
> +<!--[if lt IE 7]>      <html lang="en" ng-app="wBooksApp" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
remove IE lines

2018-12-30 02:26 UTC, FrankIglesias commented on app/scss/w-input.scss
> +  display: inline-flex;
flex?

2018-12-30 02:26 UTC, FrankIglesias commented on app/index.html
> +  <!-- In production use:
same

2018-12-30 02:26 UTC, FrankIglesias commented on app/index.html
> +  <!-- <ul class="menu">
same

2018-12-30 02:28 UTC, FrankIglesias commented on app/books/books.component.js
> +      ctrl.books = [
Think about moving this array to a json file

2019-01-02 14:47 UTC, eledwinn commented on app/scss/equalizer.scss
> +$equalizer-black: #000;
This is in the branch "wolox-gulp"

2019-01-02 14:51 UTC, eledwinn commented on package.json
> +    "postinstall": "npm run copy-libs",
This is in the branch "books-gulp"

2019-01-02 14:52 UTC, eledwinn commented on app/index.html
> +<!--[if lt IE 7]>      <html lang="en" ng-app="wBooksApp" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
This is in the "books-pug" branch

2019-01-02 14:55 UTC, eledwinn commented on app/index.html
> +  <!-- In production use:
This is in the "books-pug" branch

2019-01-02 14:55 UTC, eledwinn commented on app/index.html
> +  <!-- <ul class="menu">
This is in the "books-pug" branch

2019-01-02 15:02 UTC, eledwinn commented on app/books/books.component.js
> +      ctrl.books = [
This is in the "books-gulp" branch

2019-01-04 13:17 UTC, FrankIglesias approved these changes

2019-01-04 13:17 UTC, merged