Books detail
wolox-training/eg-angular-js pull request #12
Opened 2018-12-27 20:17 UTC by eledwinn

## Summary

1. Add ui-router
2. Add book detail page
3. Refactor book box component (book-item)

## Screenshot
![image](https://user-images.githubusercontent.com/2124740/50493284-7d423900-09ea-11e9-96eb-a14bbebb3cd7.png)

## Trello Card
https://trello.com/c/waEXCySZ/17-book-detail

2019-01-04 14:06 UTC, FrankIglesias requested changes

2019-01-04 14:06 UTC, FrankIglesias commented on .gitignore
> +.idea
add EOL

2019-01-04 14:06 UTC, FrankIglesias commented on app/app.js
> +// Declare app level module which depends on views, and core components
delete this comment

2019-01-04 14:06 UTC, FrankIglesias commented on app/app.js
> +  // An array of state definitions
same

2019-01-04 14:06 UTC, FrankIglesias commented on app/book-detail/book-detail.template.html
> +  <hr class="main-body splitter">
use a border for this

2019-01-04 14:06 UTC, FrankIglesias commented on app/book-detail/book-detail.template.html
> +  <div class="main-body">
move the margin o whatever style you are applying to the subtitle

2019-01-04 14:06 UTC, FrankIglesias commented on app/book-detail/book-detail.template.html
> +  <hr class="main-body splitter">
use a border for this

2019-01-04 14:06 UTC, FrankIglesias commented on app/common/w-input/w-input.template.html
> +    <span class="fa fa-search"></span>
This is for the icon isn't it? Add the class to the button instead

2019-01-04 14:06 UTC, FrankIglesias commented on app/common/w-input/w-input.template.html
> +
delete extra line

2019-01-04 14:06 UTC, FrankIglesias commented on app/index.html
> +  <!-- <ul class="menu">
remove some extra comments

2019-01-04 14:06 UTC, FrankIglesias commented on app/scss/book-detail.scss
> +.book-detail-author, .book-detail-year {
.book-detail-author,
book-detail-year {
}

2019-01-04 14:06 UTC, FrankIglesias commented on app/scss/book-detail.scss
> +    font-size: 1.1rem;
use px

2019-01-04 14:06 UTC, FrankIglesias commented on app/scss/book-detail.scss
> +  font-size: 1.2rem;
use px

2019-01-04 14:06 UTC, FrankIglesias commented on app/scss/book-detail.scss
> +  font-size: 1.5rem;
use px

2019-01-04 14:06 UTC, FrankIglesias commented on app/scss/book-item.scss
> +  margin: 0 30px 30px 30px;
margin: 0 30px 30px;

2019-01-04 14:06 UTC, FrankIglesias commented on app/scss/equalizer.scss
> +$equalizer-black: #000;
use [wolox equalizer ](https://www.npmjs.com/package/wolox-equalizer)

2019-01-04 14:06 UTC, FrankIglesias commented on app/app.js
> +
delete extra line

2019-01-04 14:06 UTC, FrankIglesias commented on app/app.js
> +'use strict';
Delete comments of this file

2019-01-04 14:06 UTC, FrankIglesias commented on app/scss/styles.scss
> +* {
maybe you will have to divide this classes into separate files according to it's usage

2019-01-04 14:06 UTC, FrankIglesias commented on app/scss/w-input.scss
> +  .fa {
why this is fa?

2019-01-04 14:06 UTC, FrankIglesias commented on app/scss/w-input.scss
> +  /* reset */
this should be equalizer's job

2019-01-04 14:06 UTC, FrankIglesias commented on app/scss/w-input.scss
> +  text-shadow: 0 0 0 #000;
use color variable

2019-01-04 14:06 UTC, FrankIglesias commented on package.json
> +    "postinstall": "npm run copy-libs",
delete some extra scripts

2019-01-04 16:59 UTC, eledwinn commented on app/index.html
> +  <!-- <ul class="menu">
This is ready in "books-pug" branch

2019-01-04 17:58 UTC, eledwinn commented on package.json
> +    "postinstall": "npm run copy-libs",
This is ready in "books-gulp" branch

2019-01-08 19:33 UTC, FrankIglesias requested changes

2019-01-08 19:33 UTC, FrankIglesias commented on app/book-item/book-item.component.js
> +
delete this line

2019-01-08 19:33 UTC, FrankIglesias commented on app/scss/book-item.scss
> +.book-items, .book-items-inline {
.book-items,
.book-items-inline

2019-01-08 19:33 UTC, FrankIglesias commented on app/scss/subtitle.scss
> +  font-size: 1.3rem;
use px

2019-01-08 19:36 UTC, eledwinn commented on app/book-item/book-item.component.js
> +
This is ready in books-bootstrap branch

2019-01-08 19:36 UTC, eledwinn commented on app/scss/book-item.scss
> +.book-items, .book-items-inline {
This is ready in books-bootstrap branch

2019-01-08 19:37 UTC, eledwinn commented on app/scss/subtitle.scss
> +  font-size: 1.3rem;
This is ready in books-bootstrap branch

2019-01-09 02:49 UTC, FrankIglesias approved these changes

2019-01-09 15:11 UTC, merged