Api and books
wolox-training/eg-angular-js pull request #22
Opened 2019-03-12 16:55 UTC by eledwinn

## Summary
- Add apisauce as service for get books
- Show books

## Screenshots
![image](https://user-images.githubusercontent.com/2124740/54219497-a3418a80-44bd-11e9-9c70-cbf32557d3d7.png)

## Trello Card
https://trello.com/c/1ZUMICnb/15-vue-components

2019-03-12 17:15 UTC, FrankIglesias requested changes

2019-03-12 17:15 UTC, FrankIglesias commented on src/components/books/BookItem.vue
> +    p.book-item-title(v-if='!small')
maybe you can wrap this into something else to do the v-if condition instead of repeating it

2019-03-12 17:15 UTC, FrankIglesias commented on src/components/books/BookItem.vue
> +      required: false,
remove this required

2019-03-12 17:15 UTC, FrankIglesias commented on src/components/books/Books.vue
> +const BookItem = () => import(/* webpackChunkName: "book-item" */ './../../components/books/BookItem')
only import this way the components that are part of the routes

2019-03-12 17:15 UTC, FrankIglesias commented on src/components/books/Books.vue
> +  components: {
move this components to the bottom of the object

2019-03-12 17:15 UTC, FrankIglesias commented on src/components/books/Books.vue
> +    TechsService.get().then(response => {
move this to a created() state

2019-03-12 17:15 UTC, FrankIglesias commented on src/scss/layout.scss
> +.pad-l-three {
Try something like what is proposed [here](https://github.com/Wolox/layout/pull/1)

2019-03-12 17:15 UTC, FrankIglesias commented on src/services/books.service.js
> +  baseURL: 'http://demo2269650.mockable.io',
move this into a .env variable

2019-03-12 17:15 UTC, FrankIglesias commented on src/services/books.service.js
> +  get() {
use arrow here

2019-03-12 17:15 UTC, FrankIglesias commented on src/components/Navbar.vue
> +.navbar-container {
missing position fixed?

2019-03-12 17:15 UTC, FrankIglesias commented on src/scss/layout.scss
> +.main-body-medium {
are you using this class?

2019-03-12 17:15 UTC, FrankIglesias commented on src/components/books/BookItem.vue
> +    img.book-item-image(alt='book image' src='' v-bind:src='book.image_url || "assets/book_logo.png"')
why are you doing this `src=""` why not `:src="book.image_url || "assets/book_logo.png'"` did you try adding a comma before the `:src`??

2019-03-12 17:15 UTC, FrankIglesias commented on src/components/books/BookItem.vue
> +    img.book-item-image(alt='book image' src='' v-bind:src='book.image_url || "assets/book_logo.png"')
Maybe the alt can be related to the book itself

2019-03-12 17:15 UTC, FrankIglesias commented on src/components/books/BookItem.vue
> +      small: null
false instead?

2019-03-12 17:15 UTC, FrankIglesias commented on src/components/books/BookItem.vue
> +      small: null
If you are not going to change the data from a function, you can move this small to a prop instead i think 🤔

2019-03-12 17:15 UTC, FrankIglesias commented on src/scss/layout.scss
> +.page-title-center {
you can rename this class to a more related to it's value like `.centered-text`

2019-03-12 17:16 UTC, FrankIglesias commented on src/components/books/BookItem.vue
> +    img.book-item-image(alt='book image' src='' v-bind:src='book.image_url || "assets/book_logo.png"')
you can set this "assets/book_logo.png" as a default prop

2019-03-16 15:50 UTC, FrankIglesias requested changes

2019-03-16 15:50 UTC, FrankIglesias commented on src/scss/layout.scss
> +  display: block;
do you need this?

2019-03-16 15:50 UTC, FrankIglesias commented on src/components/books/BookItem.vue
> +      default: undefined
you can set the default image here

2019-03-16 15:50 UTC, FrankIglesias commented on src/components/books/BookItem.vue
> +      defaultImage: bookLogo
data is usually used for things that are mutable

2019-03-19 14:00 UTC, FrankIglesias requested changes

2019-03-19 14:00 UTC, FrankIglesias commented on src/components/Navbar.vue
> +.navbar-container
nav here but it's ok

2019-03-19 14:00 UTC, FrankIglesias commented on src/components/Navbar.vue
> +  padding: 0px 30px;
remove px from 0

2019-03-19 14:00 UTC, FrankIglesias commented on src/components/books/BookItem.vue
> +a(href='#')
This link is edited in  other pr isn't it?

2019-03-19 14:07 UTC, eledwinn commented on src/components/books/BookItem.vue
> +a(href='#')
No... tag 'a' removed

2019-03-19 14:15 UTC, FrankIglesias requested changes

2019-03-19 14:15 UTC, FrankIglesias commented on src/components/books/BookItem.vue
> +      default: undefined
`() => ({ image_url: defaultImage })` instead

2019-03-19 15:57 UTC, FrankIglesias approved these changes

2019-03-19 16:07 UTC, merged